create table student
(
    id        int generated by default as identity primary key,
    name      varchar(32)        not null,
    lastname  varchar(32)        not null,
    email     varchar(64) unique not null,
    username  varchar(32) unique not null,
    password  varchar            not null,
    role      varchar,
    is_enable boolean
);

select *
from student;

create table activtion
(
    id    int generated by default as identity primary key,
    key   varchar,
    email varchar
);